### ISSUE TITLE
Phase 3: Modify the SPARQL to include the series and the series-agency relationships in the two CSV tables

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-RIF-SPARQL#11]

**Comment by Conal-Tuohy** [comment]
This is actually a bit trickier than I thought. 

To avoid confusing myself, I'm going to change the format of the CSV data files, because they have columns which were not well named. This is because they used the same file format as the original manually-produced files. In that format there was a column in nodes.csv called FUNCTION which actually included the names of both functions AND agencies. That was already bad enough, but it will be even worse if it also contains series.

So I will first rationalize the file format, and change the JS to match, and _then_ I will add the series-agency relationships.

**Comment by asaletourneau** [comment]
Thanks so much for doing this Conal. I guess we had no idea where this was going when we started off u sing the manually created CSV files. So glad we made the decision to go the API dynamic update route and you had the skills to make it happen. Will be able to breathe a huge sigh of relief when Kaz finally gets those missing 197 functions into the JAOI repository!

**Comment by Conal-Tuohy** [comment]
completed in revision fa591c1a1a2e41f264b5ba0a8616ff2ef8b5f3d9
