### ISSUE TITLE
bug with searching by date for nodes  missing start date 

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-RIF-SPARQL#14]
Both Acess the Collection and the rif-cs state contents in custody date range for Series 8935 as circa 1860- 1992
And the screenshot below shows that a valid date search within the series contents in custody date range returns no match:
![circa date bug](https://cloud.githubusercontent.com/assets/1021209/15564525/83ad101c-2356-11e6-96c3-ef65f6d627b2.jpg)

**Comment by Conal-Tuohy** [comment]
I have debugged this and I found series VPRS 8935 doesn't show up when specifying a date of 1860 because objects are only included along with a related object, and both objects must match the date filter (if there is a date filter specified). The only two objects that VPRS 8935 is connected to (VA 1041 and VA 3154) have date ranges that don't include 1860. 

If that seems OK to you, @asaletourneau , then close this ticket.

Otherwise, we need to revise the way the search works.

**Comment by Conal-Tuohy** [comment]
Should "orphaned" nodes be allowed on the visualization, with no relationships? In some ways the point of the visualization is to present context, and these are precisely the nodes without much context. Despite that, such nodes would be valid search results in their own right.

**Comment by asaletourneau** [comment]
The real issue for me is not so much around orphaned works but the date search not working for any related nodes with a circa or '?' before the date.
