### ISSUE TITLE
Data missing in OAI-PMH provider

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/PROV-RIF-SPARQL#5]
The OAI-PMH server is not publishing all the records which we used to have in the previously prepared dataset. In particular, although we have slightly more agencies, we have less than half the number of functions (blue, in the network diagrams) we had before.

Original network:
![original-network](https://cloud.githubusercontent.com/assets/1264711/12343994/95c93440-bb84-11e5-9487-82adac414051.png)

New (OAI-PMH harvested) network
![oai-pmh-network](https://cloud.githubusercontent.com/assets/1264711/12343995/95f4e4aa-bb84-11e5-863e-3734a14b229a.png)

**Comment by Conal-Tuohy** [comment]
My first suspect is PROV's jOAI provider: it may have failed to index these function records due to a lack of memory.

**Comment by asaletourneau** [comment]
Hi, just finished lunch and read through all your emails. I'm wondering if
you might be able to email kazuki.tada@prov.vic.gov.au directly about the
missing Functions issue to see if he can do anything about it.? Strangely
it might actually get things done if an external request like this comes
through. Just CC me in so I'm across it.

Cheers

Asa Letourneau
Online Engagement  Officer, Public Record Office Victoria
03 9348 5759 I  0423 482 127 I  fax 03 9348 5656
asa.letourneau@prov.vic.gov.au
Public Record Office Victoria
Victorian Archives Centre | 99 Shiel St North Melbourne VIC 3051

Our offices are located on the land of the Kulin Nations.
We acknowledge and pay our respect to the Traditional Owners, past and
present.

PROV News | http://prov.vic.gov.au/publications/blog
Events | http://prov.vic.gov.au/whats-on
Battle to Farm | http://soldiersettlement.prov.vic.gov.au/

Please note I work from home on Mondays

You must  not copy, disclose, distribute, store or otherwise use this
material without permission. Any personal information in this email must be
handled in accordance with the Information Privacy Act 2000 (Vic) and
applicable laws. If you are not the intended recipient, please notify the
sender immediately and destroy all copies of this email and any
attachments. The State does not accept liability in connection with
computer viruses, data corruption, delay, interruption, unauthorised access
or use.

**Comment by asaletourneau** [comment]
The JAOI repository states 139 functions exist.
Charlie Farrugia's reports from Archives One state 322 functions exist.
A manual count from this Access the Collection page state 336 functions exist. 
We know that once the true number of Functions is made available the PROVisualizer will reflect this.

**Comment by Conal-Tuohy** [comment]
I think the error is that the code that exports the RIF-CS from Archives One is filtering out these functions. I think the error is here:
http://sourceforge.net/projects/governmentarchivesmetadata/files/excl_function_proc.sql/download
NB functions are excluded if their description is blank, and I note that one of the functions reported missing [VF 418](http://www.access.prov.vic.gov.au/public/component/daPublicBaseContainer?component=daViewFunction&breadcrumbPath=Home/Access%20the%20Collection/Browse%20The%20Collection/Function%20Details&entityId=418) has no description.

**Comment by Conal-Tuohy** [comment]
Assuming my diagnosis is correct, a solution is to ensure that all functions (and agencies) have descriptions.

**Comment by asaletourneau** [comment]
Working from home and just saw this. Are you able to email or call Kaz about this? His email will be kazuki.tada@prov.vic.gov.au but I don't have his landline with me. Sorry :(

**Comment by Conal-Tuohy** [comment]
I have emailed him, but no response yet. 

In the meantime, something that you could maybe arrange independently is to ensure that the functions in Archives One are all assigned a description, even if it's rudimentary.

**Comment by Conal-Tuohy** [comment]
Closing this issue, as agreed. 

It seems likely that at some stage the function filter may be relaxed, and some more functions will flow through the OAI-PMH repository into the visualizer, but that is an internal matter for PROV.
