### ISSUE TITLE
Apostrophe escape characters

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-RIF-SPARQL#6]
Apostrophe escape characters appearing  in Function drop down label list as well as Function node titles within visualization. Is there any way to avoid this happening so users are not confused?
![untitled](https://cloud.githubusercontent.com/assets/1021209/12410391/c0adaac8-bec8-11e5-9f52-02b8774462ba.jpg)

**Comment by Conal-Tuohy** [comment]
Here's another one, the [Court of Petty Sessions/Magistrates&amp;#039; Court Register](https://researchdata.ands.org.au/registry/services/oai?verb=GetRecord&metadataPrefix=rif&identifier=oai:ands.org.au::148449)

The error is that when the RIF-CS XML files were generated, the apostrophe character `'` has been serialized as `&039;` (presumably this is in case it appeared within an XML attribute value, but this will not happen in RIF-CS so this step is unnecessary), and then the initial `&` has been escaped as `&amp;`, turning the `039` character code into literal text. 

Again, the problem should be fixed upstream.

However, a workaround could be to replace any sequence of `&amp;#nnn;` with the actual `nnn` character, when converting the harvested data to RDF. Presumably ANDS are doing a similar cleanup on their site, because this record for instance shows an apostrophe correctly: https://researchdata.ands.org.au/court-petty-sessionsmagistrates039-court-register/148449/

**Comment by asaletourneau** [comment]
Thanks for the explanation.I guess the only thing is that we don't see any of these escaped characters when we go public March 15. In an ideal world it would be great to at least experience the viz without them before that date if at all possible? Though that might be hard given you've already harvested all the ANDS data containing them oin the XML?

**Comment by Conal-Tuohy** [comment]
updated stylesheet to "unescape" any such characters.

**Comment by asaletourneau** [comment]
Sorry for bothering you again Conal even though you're on a break. Now that you've updated the stylesheet, I'm assuming the changes won't be visible until ? Just had a look now and the escaped character still appearing in both Function drop down list and Agency node label:
![apostrophe](https://cloud.githubusercontent.com/assets/1021209/12439763/8ebed904-bf88-11e5-8b03-725adec11f78.jpg)

**Comment by Conal-Tuohy** [comment]
It won't be visible until the SPARQL queries are run to regenerate the CSV files. It is visible now in the RDF though, e.g. http://prov-data.conaltuohy.com/fuseki/prov/data?graph=oai%253Aands.org.au%253A%253A148449

**Comment by asaletourneau** [comment]
Wonderful! Any idea when the SPARQL queries will be run again?

**Comment by asaletourneau** [comment]
SorVA 1456, VA 4867, VA 518ry but jusat noticed that while VA 4019, VA 1456, VA 4867, VA 518 all in appear in the XML, only VA 1456, VA 4867, VA 518 appear in the visualisation. I know I'm adding an additional issue within this escaped apostrophe one but I'm dashing into a meeting in 30 seconds!!!

**Comment by asaletourneau** [comment]
I'm an idiot... that shpould have read:
Sorry but just noticed that while VA 4019, VA 1456, VA 4867, VA 518 all in appear in the XML, only VA 1456, VA 4867, VA 518 appear in the visualisation. I know I'm adding an additional issue within this escaped apostrophe one but I'm dashing into a meeting in 30 seconds!!!
