### ISSUE TITLE
Missing VA despite data being available

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-RIF-SPARQL#8]
In hindsight I thought I better create a separate issue for this instead of sticking it in with the Apostrphe issue:
Noticed that while VA 4019, VA 1456, VA 4867, VA 518 all in appear in the XML and the JAOI repository, only VA 1456, VA 4867, VA 518 appear in the visualisation.

**Comment by Conal-Tuohy** [comment]
`VA 4019` appears not to have any functions attached. This SPARQL query shows all that is known about `VA 4019`:
http://prov-data.conaltuohy.com/fuseki/dataset.html?tab=query&ds=%2Fprov&query=select+%3Frelated+where%0A%7B%0A++%7B%0A%09++%3Frelated+%3Frelation+%3Chttp%3A%2F%2Fprov-data.conaltuohy.com%2Fresource%2FPROV%2520VA%25204019%3E%0A++%7D%0A++union%0A++%7B%0A%09++%3Chttp%3A%2F%2Fprov-data.conaltuohy.com%2Fresource%2FPROV%2520VA%25204019%3E+%3Frelation+%3Frelated%0A++%7D%0A%7D

It is linked to various curation activities (i.e. the creation of various collections - these data were harvested from the RIF-CS collection records that mention `VA 4019`), and it has a name and identifier, a link to the catalogue, and start and end dates.

Perhaps this relates to issue #5 which is about missing functions. If all of an agencies functions are missing, then the agency itself will disappear from the visualization, because the visualization only covers agency/function relationships.

I checked http://www.access.prov.vic.gov.au/public/component/daPublicBaseContainer?component=daViewAgency&entityId=4019 and did not see any functions listed there either.

@asaletourneau can you chase this agency up and see what data we should have?

**Comment by asaletourneau** [comment]
Thanks very much for the clarification. And yes that makes total sense that we are purely showing Agency?Function relationships so we won't show Agencies not attached to a Function. I've confirmed with a colleague that Functions don't necessarily have to be ascribed to an Agency so we may have quite a few 'gaps' in Archives One.
